### PR TITLE
Fix: Error message of `add` and `edit` command

### LINKED ISSUE #179: [PE-D][Tester C] Add Command Usage Message shows all parameters as required, but most are optional
### Description
The Add Command Usage Message displays:
```
add: Adds a person to the address book. Parameters: -r ROLE -n NAME -p PHONE -e EMAIL -a ADDRESS [-t TAG]...
```
Only `-t TAG` is shown with square brackets (optional), but the UG makes clear that `-r`, `-p`, `-e`, and `-a` are all optional. The error message misrepresents the command format. Only `-n NAME` is actually required.

### Steps to Reproduce
1. Run an invalid `add` command (e.g., `add` with no arguments).
2. Observe the error message shows `-r ROLE -n NAME -p PHONE -e EMAIL -a ADDRESS` all as if required.

### Expected Behavior
The usage message should use square brackets for optional parameters: `add [-r ROLE] -n NAME [-p PHONE] [-e EMAIL] [-a ADDRESS] [-t TAG]...`

### Actual Behavior
All fields except `-t` are shown as required in the error message.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`

### LINKED ISSUE #189: [PE-D][Tester A] Inconsistent format for optional fields
Image

Image

Should [-rROLE] [-nNAME] [-pPHONE] [-eEMAIL] [-aADDRESS] [-tTAG] be [-r ROLE] [-n NAME] [-p PHONE] [-e EMAIL] [-a ADDRESS] [-t TAG] instead? where there is a space

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`

### LINKED ISSUE #190: [PE-D][Tester A] Inconsistent error message for add
Image

Image

Optional fields are not correctly pointed out in the error message ( -r ROLE -p PHONE -e EMAIL -a ADDRESS) , inconsistent with the UG ([-r ROLE] [-p PHONE_NUMBER] [-e EMAIL] [-a ADDRESS])

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #191: [PE-D][Tester A] Edit error message example inconsistent with other commands' examples
Image

Should be edit 1 -p 91234567 -e johndoe@example.com (with a space)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`

### LINKED ISSUE #211: [PE-D][Tester B] Mismatch between UG and Add command error message
System specs:
OS: Windows 11
Monitor size: 16inch
Display resolution: 1920x1200
Scale: 125%

Description:
In the add command error message, it states that only the Tags parameter is optional. However, the actual behavior as stated in the UG is that the only required field is name, and the rest are all optional.

Steps to reproduce:
1. `add`

Expected result:
System should display an error message that properly reflects the actual behavior, where only Name is required
add [-r ROLE] -n NAME [-p PHONE_NUMBER] [-e EMAIL] [-a ADDRESS] [-t TAG]

Actual result:
System displays an error message where only Tags are optional
Image

-------------
Labels: `severity.Low` `type.FunctionalityBug`

### LINKED ISSUE #213: [PE-D][Tester E] add command error message displays incorrect and misleading parameter constraints
**Description:
Steps to reproduce:**

1. Trigger the add command's format error message (e.g., by typing add with no parameters or an invalid prefix).
2. Observe the terminal output format instructions.

Expected Behavior:
The terminal output should exactly match the format specified in the User Guide: add [-r ROLE] -n NAME [-p PHONE_NUMBER] [-e EMAIL] [-a ADDRESS] [-t TAG].... It indicate that Role, Phone, Email, and Address are optional (enclosed in square brackets) and include proper spacing for the tags.

Actual Behavior:
The terminal outputs the following format string:
Parameters: -r ROLE -n NAME -p PHONE -e EMAIL -a ADDRESS [-tTAG]...

This output contains two errors:

1. It omits the square brackets for -r, -p, -e, and -a, falsely implying to the user that these fields are strictly mandatory.
2. It is missing a space between -t and TAG ([-tTAG]...).

Why this is problematic:
While this is a terminal output issue, it actively misleads the user. A user relying on the terminal's built-in help message will assume they must provide a Role, Phone, Email, and Address to add a contact, which completely contradicts the User Guide's instruction that these fields are optional.

-------------
Labels: `severity.Medium` `type.FunctionalityBug`

### LINKED ISSUE #239: [PE-D][Tester D] Add command error usage text marks optional fields as mandatory
Actual: The runtime usage string for add lists role, phone, email, and address as required (as they are not enclosed in square brackets), however, these fields are in fact optional as only Name is required.

Expected: The error help message should reflect the actual optional/required fields.

Steps:
1. Use an incomplete add command e.g. `add`
Image

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`

### PR DESCRIPTION
**Pull request by vietquang1006**
Error message of `add` command now shows correct optional fields with square brackets.
Error message of `edit` command now shows correct message.

Fixes #179 
Fixes #189 
Fixes #190 
Fixes #191 
Fixes #211 
Fixes #213 
Fixes #239

### CODE REVIEW

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 1]
```diff
@@ -22,11 +22,11 @@ public class AddCommand extends Command {
 
     public static final String MESSAGE_USAGE = COMMAND_WORD + ": Adds a person to the address book. "
             + "Parameters: "
-            + PREFIX_ROLE + " ROLE "
+            + "[" + PREFIX_ROLE + " ROLE] "
```
Comment (henghengyh) [inline src/main/java/seedu/address/logic/commands/AddCommand.java:25]: Good catch!

**Review by henghengyh — APPROVED** [review]
LGTM.

File: src/main/java/seedu/address/logic/commands/EditCommand.java [hunk 2]
```diff
@@ -41,15 +41,15 @@ public class EditCommand extends Command {
...
             + "Existing values will be overwritten by the input values.\n"
             + "Parameters: INDEX (must be a positive integer) "
-            + "[" + PREFIX_ROLE + "ROLE] "
-            + "[" + PREFIX_NAME + "NAME] "
-            + "[" + PREFIX_PHONE + "PHONE] "
-            + "[" + PREFIX_EMAIL + "EMAIL] "
-            + "[" + PREFIX_ADDRESS + "ADDRESS] "
-            + "[" + PREFIX_TAG + "TAG]...\n"
+            + "[" + PREFIX_ROLE + " ROLE] "
+            + "[" + PREFIX_NAME + " NAME] "
```
Comment (natsupercell) [inline src/main/java/seedu/address/logic/commands/EditCommand.java:45]: please change this, name is not optional

File: src/main/java/seedu/address/logic/commands/AddCommand.java [hunk 3]
```diff
@@ -22,11 +22,11 @@ public class AddCommand extends Command {
...
             + PREFIX_NAME + " NAME "
-            + PREFIX_PHONE + " PHONE "
-            + PREFIX_EMAIL + " EMAIL "
-            + PREFIX_ADDRESS + " ADDRESS "
+            + "[" + PREFIX_PHONE + " PHONE] "
+            + "[" + PREFIX_EMAIL + " EMAIL] "
+            + "[" + PREFIX_ADDRESS + " ADDRESS] "
             + "[" + PREFIX_TAG + "TAG]...\n"
```
Comment (natsupercell) [inline src/main/java/seedu/address/logic/commands/AddCommand.java]: please add spacing here also, for consistency

**Review by natsupercell — CHANGES_REQUESTED** [review]
Please correct these:

Image

Currently edit message shows that name field is optional, which is not.

Image

Add message looks good to me overall, but I would suggest a small change to what is currently `[-tTAG]` to `[-t TAG]`

File: src/main/java/seedu/address/logic/commands/EditCommand.java (hunk 2 above)
Comment (natsupercell) [reply src/main/java/seedu/address/logic/commands/EditCommand.java:45]: my mistake, name field is optional in edit command, so this is good

File: src/main/java/seedu/address/logic/commands/AddCommand.java (hunk 3 above)
Comment (vietquang1006) [reply src/main/java/seedu/address/logic/commands/AddCommand.java]: done

**Review by natsupercell — APPROVED** [review]
LGTM. Tested locally and ensured messages are displayed correctly
good job!
