### PR TITLE
Fixes #175: Fix bug change name format

### LINKED ISSUE #175: [PE-D][Tester C] Names cannot contain hyphens, apostrophes, or s/o
### Description
The `Name` validation only allows alphanumeric characters and spaces. This blocks many legitimate real-world names:
- **Hyphenated names:** `Mary-Anne`, `Lee Kuan-Yew`
- **Names with apostrophes:** `O'Brien`, `D'Souza`
- **Malay naming convention:** `Ahmad s/o Ibrahim` (son of)
- **Names with periods:** `Dr. John`, `St. James`

For an NUS student address book targeting SEA demographics, `/` in names (e.g., `s/o`) and other common characters are especially important.

### Steps to Reproduce
1. `add -n Mary-Anne -p 91234567`
2. Error: "Names should only contain alphanumeric characters and spaces, and it should not be blank"

### Expected Behavior
Names with hyphens, apostrophes, periods, and slashes should be accepted (or at least warned about, not blocked).

### Actual Behavior
They are rejected entirely.

-------------
Labels: `severity.Low` `type.FeatureFlaw`

### PR DESCRIPTION
**Pull request by natsupercell**
This PR updates name validation to support common real-world punctuation, and aligns the related logic, tests, and documentation with the new behavior.

Changes made:
- Relaxed `Name` validation to allow common punctuation such as `.`, `'`, `/`, and `-`.
- Updated name-keyword validation in `find` so punctuation-containing names can be searched consistently.
- Revised the related user-facing validation message to reflect the new accepted format.
- Updated tests for `Name` and `NameContainsKeywordsPredicate` to cover the relaxed validation rules.
- Updated the User Guide and Developer Guide to document the new behavior and examples.

Reviewer to check:
- [ ] Names with common punctuation such as `Mary-Anne`, `O'Brien`, `Dr. John`, and `Ahmad s/o Ibrahim` are accepted
- [ ] `find` supports name keywords with the same allowed punctuation
- [ ] Invalid characters such as `!` and `*` are still rejected
- [ ] The updated validation message matches the current implementation
- [ ] The User Guide and Developer Guide are consistent with the new behavior
- [ ] the PR is sent from a fork, and is from a separate branch
- [ ] commit messages comply with the [Git Conventions](https://nus-cs2103-ay2526-s2.github.io/website/admin/standardsAndConventions.html)

Fixes #175

### CODE REVIEW

File: src/main/java/seedu/address/logic/Messages.java [hunk 1]
```diff
@@ -21,6 +21,9 @@ public class Messages {
     public static final String MESSAGE_DUPLICATE_FIELDS =
                 "Multiple values specified for the following single-valued field(s): ";
     public static final String MESSAGE_CONTAINS_NON_ALPHANUMERIC_CHARACTER = "Only give alphanumeric keywords";
+    public static final String MESSAGE_INVALID_NAME_KEYWORD =
```
Comment (henghengyh) [inline src/main/java/seedu/address/logic/Messages.java:24]: I like this edit

File: src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java [hunk 2]
```diff
@@ -35,7 +35,7 @@ public NameContainsKeywordsPredicate(List<String> keywords) throws CommandExcept
      */
     public NameContainsKeywordsPredicate(List<String> keywords, KeywordRelation relation) throws CommandException {
         if (keywords.stream().anyMatch(keyword -> !keyword.matches(KEYWORD_VALIDATION_REGEX))) {
-            throw new CommandException(Messages.MESSAGE_CONTAINS_NON_ALPHANUMERIC_CHARACTER);
+            throw new CommandException(Messages.MESSAGE_INVALID_NAME_KEYWORD);
```
Comment (henghengyh) [inline src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java:38]: Good clarification that we accept some non-alphanumeric characters

File: src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java [hunk 3]
```diff
@@ -72,6 +73,19 @@ public void test_nameContainsKeywords_returnsTrue() throws CommandException {
         // Multi-word keyword phrase
         predicate = new NameContainsKeywordsPredicate(Collections.singletonList("alice bob"));
         assertTrue(predicate.test(new PersonBuilder().withName("Alice Bob").build()));
+
```
Comment (henghengyh) [inline src/test/java/seedu/address/model/person/NameContainsKeywordsPredicateTest.java:76]: Good test coverage added.

File: build.gradle [hunk 4]
```diff
@@ -46,35 +46,35 @@ task coverage(type: JacocoReport) {
 }
 
 dependencies {
```
Comment (henghengyh) [inline build.gradle:48]: Do not make edits to build.gradle

**Review by henghengyh — CHANGES_REQUESTED** [review]
Do not make edits to build.gradle

**Review by henghengyh — APPROVED** [review]
LGTM no edits to `build.gradle`.

**Review by vietquang1006 — APPROVED** [review]
LGTM
